Authenticate against a server without Basic HTTP auth
Arello-Mobile/confluence-publisher pull request #6
Opened 2017-01-12 16:26 UTC by hojalot

Our Confluence server does not have Basic HTTP authentication enabled.  Setting the requests.Session user and password allows authentication with our server to work.

I also found that our Sphinx-generated html <title> was multi-line, so I added DOTALL to the regexp.

In order not to change the existing code structure too much, I ended up returning either a string (the base64 encoded user:pass), or the requests.Session object from parse_authentication().  Not sure if this is too weird or not.

I've only lightly tested against our Confluence server, and not against a server with Basic HTTP auth.

2017-01-12 17:22 UTC, SimplicityGuy requested changes

2017-01-12 17:22 UTC, SimplicityGuy commented on conf_publisher/confluence_api.py
> +            self.s = None
Perhaps renaming `self.s` to `self.session` would be a bit clearer.

2017-01-12 17:22 UTC, SimplicityGuy commented on conf_publisher/page_dumper.py
> +    parser.add_argument('-t', '--auth-type', type=str, help='"basic" or "session" authentication')
Would recommend limiting this to one of a few choices. See https://docs.python.org/2/library/argparse.html, section "15.4.3.7. choices"

2017-01-12 17:22 UTC, SimplicityGuy commented on conf_publisher/auth.py
> +        else:
This will always fall-through even if the user passes in a bad input. See other feedback about using `choices` for `argparse`.

2017-01-13 17:51 UTC, hojalot commented on conf_publisher/confluence_api.py
> +            self.s = None
Done

2017-01-13 17:52 UTC, hojalot commented on conf_publisher/page_dumper.py
> +    parser.add_argument('-t', '--auth-type', type=str, help='"basic" or "session" authentication')
Good idea.  Done

2017-04-07 04:52 UTC, merged

2017-04-07 04:55 UTC, c1rno commented
@hojalot can you check is auth working in you case now?

2017-04-10 21:22 UTC, hojalot commented
I see that the refactoring of my changes removed the --auth-type option, so I ran just with "conf_publisher publish.yml -v -U $USER", but I get this error:

Publishing attachments...
Publishing attachment: /path/to/my/doc/dir/_build/html/_images/image.svg (parent_id: 88869910)
Traceback (most recent call last):
  File "/usr/local/bin/conf_publisher", line 9, in <module>
    load_entry_point('confluence-publisher==1.2.2', 'console_scripts', 'conf_publisher')()
  File "build/bdist.linux-x86_64/egg/conf_publisher/publish.py", line 195, in main
  File "build/bdist.linux-x86_64/egg/conf_publisher/publish.py", line 126, in publish
  File "build/bdist.linux-x86_64/egg/conf_publisher/publish.py", line 139, in _publish_attachments
  File "build/bdist.linux-x86_64/egg/conf_publisher/publish.py", line 143, in _publish_page_attachement
  File "build/bdist.linux-x86_64/egg/conf_publisher/confluence.py", line 186, in publish
TypeError: list object is not an iterator

I added 'print "filter:",filter(lambda x: x.title == attachment_file.filename, attachments)' in AttachmentPublisher publish() and get:
filter: [<conf_publisher.confluence.DownloadAttachement object at 0x7f34220d7e90>]

Can next() be done on a DownloadAttachement?

BTW, I am using Python 2.7.12.

2017-04-11 02:24 UTC, c1rno commented
> I see that the refactoring of my changes removed the --auth-type option, so I ran just with "conf_publisher publish.yml -v -U $USER"

Yea, you'r right, just there isn't any reason to extend cli interface. Fix that you submit just reuse cookies, but it still `basic auth`, so now publisher must work with more configurations without any actions from user-side.

And about this error, it part of code not test covered and I'm not run it in Python 2.7, but it error happens because in py2.7 filter returns list, in py3 filter returns generator; I fix it incompatibility in [981f766](https://github.com/Arello-Mobile/confluence-publisher/commit/981f766d98e6c1ae52063e310e1b838f86c5ba9d).

2017-04-11 16:00 UTC, hojalot commented
After pulling your filter fix, my publish works fine.

Thank you!